ERROR 2015-12-06 08:51:59,211 django.request base Internal Server Error: /auth/password/reset/
Traceback (most recent call last):
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/djoser/utils.py", line 57, in post
    return self.action(serializer)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/djoser/views.py", line 116, in action
    self.send_email(**self.get_send_email_kwargs(user))
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/djoser/utils.py", line 78, in get_send_email_kwargs
    'context': self.get_email_context(user),
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/djoser/views.py", line 127, in get_email_context
    context = super(PasswordResetView, self).get_email_context(user)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/djoser/utils.py", line 101, in get_email_context
    domain = django_settings.DJOSER['DOMAIN']
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'DJOSER'
ERROR 2015-12-06 08:51:59,211 django.request base Internal Server Error: /auth/password/reset/
Traceback (most recent call last):
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/djoser/utils.py", line 57, in post
    return self.action(serializer)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/djoser/views.py", line 116, in action
    self.send_email(**self.get_send_email_kwargs(user))
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/djoser/utils.py", line 78, in get_send_email_kwargs
    'context': self.get_email_context(user),
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/djoser/views.py", line 127, in get_email_context
    context = super(PasswordResetView, self).get_email_context(user)
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/djoser/utils.py", line 101, in get_email_context
    domain = django_settings.DJOSER['DOMAIN']
  File "/Users/junhua_liu/Playground/venv/proqodpy/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'DJOSER'
